### ISSUE TITLE
Cannot start ARMOR client

### ISSUE THREAD

**Issue by Elsenosy** [EmaroLab/armor_py_api#2]
Hello there,
I have installed armor, armor_msgs, multi_ontology_refrence, armor_py_api and more other tools to my package to handle ontology using armor in python, i installed rosjava and built it to use ARMOR, 
Then i typed a test script of my own ontology, when i run it, it triggers the following error:

`armor_api.armor_exceptions.ArmorServiceCallError: Cannot reach ARMOR client: Timeout Expired. Check if ARMOR is running.
`

Thanks

**Comment by alessio-cpt** [comment]
That message means that the armor server is not running. Make sure you followe these two steps:

1. You ran at least once the command `./gradlew deployApp` in the armor package folder.
2. Make sure to run `rosrun armor execute it.emarolab.armor.ARMORMainService` **before** you launch your script.

**Comment by Elsenosy** [comment]
I already run `run rosrun armor execute it.emarolab.armor.ARMORMainService`
but the result is 
`[rosrun] Couldn't find executable named excute below /home/taha/orca_ws/src/armor`
Do you thin the problem is when installing the package to my work space ?

**Comment by Elsenosy** [comment]
Thanks, it works correctly now.
